name: Update Memos JSON

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-memos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # 使用合适的Python版本

      - name: Install requests library
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Memos and save as JSON
        run: |
          python generate_memos_json.py

      - name: Commit and push if changed
        run: |
         git config --global user.email "action@github.com"
         git config --global user.name "GitHub Action"
         git add memos.json
         git diff --quiet && git diff --staged --quiet || (git commit -m "Update memos.json" && git push)